s3=input("What is your favourite form of social media , if you dont mind me asking?--")
if(s3=="Facebook"):
    print ("Oh, Facebook eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your facebook account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Facebook :p")
if(s3=="FFacebook"):
    print ("Oh, Facebook eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your facebook account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Facebook :p")
if(s3=="Ffacebook"):
    print ("Oh, Facebook eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your facebook account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Facebook :p")
if(s3=="FACEBOOK"):
    print ("Oh, Facebook eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your facebook account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Facebook :p")
if(s3=="Twitter"):
    print ("Oh, Twitter eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Twitter account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Twitter :p")
if(s3=="TTwitter"):
    print ("Oh, Twitter eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Twitter account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Twitter :p")
if(s3=="Ttwitter"):
    print ("Oh, Twitter eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Twitter account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Twitter :p")
if(s3=="TWITTER"):
    print ("Oh, Twitter eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Twitter account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Twitter :p")
if(s3=="Instagram"):
    print ("Oh, Instagram eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Instagram account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is   because , i dont use Instagram :p")
if(s3=="Iinstagram"):
    print ("Oh, Instagram eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Instagram account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is   because , i dont use Instagram :p")
if(s3=="IInstagram"):
    print ("Oh, Instagram eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Instagram account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is   because , i dont use Instagram :p")
if(s3=="instagram"):
    print ("Oh, Instagram eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Instagram account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is   because , i dont use Instagram :p")
if(s3=="INSTAGRAM"):
    print ("Oh, Instagram eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Instagram account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is   because , i dont use Instagram :p")
if(s3=="Pinterest"):
    print ("Oh, Pinterestn eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Pinterest account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Pinterest :p")
if(s3=="Ppinterest"):
    print ("Oh, Pinterestn eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Pinterest account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Pinterest :p")
if(s3=="PPinterest"):
    print ("Oh, Pinterestn eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Pinterest account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Pinterest :p")
if(s3=="PINTEREST"):
    print ("Oh, Pinterestn eh?")
    print(" Well thats pretty nice then !")
    f2=input("Whats your Pinterest account name,if you dont mind me asking?")
    print("So your account is ",f2,"?")
    print("thats cool ! Mine is    because , i dont use Pinterest :p")
if(s3=="Tiktok"):
    print ("Oh, Tiktok eh?")
    print(" Well thats pretty fucking cringe then!")
    print("Bro fuck off n die u cringe ass Tiktok motherfucker :|")
    print("\U0001f600","\U0001F595")   
if(s3=="Ttiktok"):
    print ("Oh, Tiktok eh?")
    print(" Well thats pretty fucking cringe then!")
    print("Bro fuck off n die u cringe ass Tiktok motherfucker :|")
    print("\U0001f600","\U0001F595")   
if(s3=="TTiktok"):
    print ("Oh, Tiktok eh?")
    print(" Well thats pretty fucking cringe then!")
    print("Bro fuck off n die u cringe ass Tiktok motherfucker :|")
    print("\U0001f600","\U0001F595")       
if(s3=="Tiktok"):
    print ("Oh, Tiktok eh?")
    print(" Well thats pretty fucking cringe then!")
    print("Bro fuck off n die u cringe ass Tiktok motherfucker :|")
    print("\U0001f600","\U0001F595")   
if(s3=="TIKTOK"):
    print ("Oh, Tiktok eh?")
    print(" Well thats pretty fucking cringe then!")
    print("Bro fuck off n die u cringe ass Tiktok motherfucker :|")
    print("\U0001f600","\U0001F595")   
if(s3=="Snapchat"):
    print ("Oh, Snapchat eh?")
    print("Well thats pretty cool then!")
    print("I dont use Snapchat tho :z but I hope you have a great time on it !")
if(s3=="Ssnapchat"):
    print ("Oh, Snapchat eh?")
    print("Well thats pretty cool then!")
    print("I dont use Snapchat tho :z but I hope you have a great time on it !")
if(s3=="SSnapchat"):
    print ("Oh, Snapchat eh?")
    print("Well thats pretty cool then!")
    print("I dont use Snapchat tho :z but I hope you have a great time on it !")
if(s3=="SNAPCHAT"):
    print ("Oh, Snapchat eh?")
    print("Well thats pretty cool then!")
    print("I dont use Snapchat tho :z but I hope you have a great time on it !")
if(s3=="Tumblr"):
    print ("Oh, Tumblr eh?")
    print("Well thats pretty cool then!")
    print("I dont use  Tumblr tho :z but I hope you have a great time on it !")
if(s3=="Ttumblr"):
    print ("Oh, Tumblr eh?")
    print("Well thats pretty cool then!")
    print("I dont use  Tumblr tho :z but I hope you have a great time on it !")
if(s3=="TTumblr"):
    print ("Oh, Tumblr eh?")
    print("Well thats pretty cool then!")
    print("I dont use  Tumblr tho :z but I hope you have a great time on it !")
if(s3=="TUMBLR"):
    print ("Oh, Tumblr eh?")
    print("Well thats pretty cool then!")
    print("I dont use  Tumblr tho :z but I hope you have a great time on it !")