except AssertionError:
except AttributeError:
except EOFError:
except FloatingPointError:
except GeneratorExit:
except IndexError:
except KeyError:
except KeyboardInterrupt:
except ModuleNotFoundError:
except MemoryError:
except NameError:
except OSError:
except OverflowError:
except ReferenceError:
except RuntimeError:
except StopIteration:
except SyntaxError:
except IndentationError:
except TabError:
except SystemError:
except SystemExit:
except TypeError:
except UnboundLocalError:
except UnicodeError:
except UnicodeEncodeError:
except UnicodeDecodeError:
except UnicodeTranslateError:
except ValueError:
except ZeroDivisionError:
 
