class Excepts:
    def AssertionError():
        except AssertionError:
    def AttributeError():
        except AttributeError:
    def EOFError():
        except EOFError:
    def FloatingPointError():
        except FloatingPointError:
    def GeneratorExit():
        except GeneratorExit:
    def IndexError():
        except IndexError:
    def KeyError():
        except KeyError:
    def KeyboardInterrupt():
        except KeyboardInterrupt:
    def ModuleNotFoundError():
        except ModuleNotFoundError:
    def MemoryError():
        except MemoryError:
    def NameError():
        except NameError:
    def OSError():
        except OSError:
    def OverflowError():
        except OverflowError:
    def ReferenceError():
        except ReferenceError:
    def RuntimeError():
        except RuntimeError:
    def StopIteration():
        except StopIteration:
    def SyntaxError():
        except SyntaxError:
    def IndentationError():
        except IndentationError:
    def TabError():
        except TabError:
    def SyntaxError():
        except SystemError:
    def SystemExit():
        except SystemExit:
    def TypeError():
        except TypeError:
    def UnboundLocalError():
        except UnboundLocalError:
    def UnicodeError():
        except UnicodeError:
    def UnicodeEncodeError():
        except UnicodeEncodeError:
    def UnicodeDecodeError():
        except UnicodeDecodeError:
    def UnicodeTranslateError():
        except UnicodeTranslateError:
    def ValueError():
        except ValueError:
    def ZeroDivisionError():
        except ZeroDivisionError:
